---
# Playbook will be ran against all hosts
- hosts: all
  # Tasks will be ran as an elevated user
  become: true
  tasks:
    # Name of the play
    - name: install apache package, php support for and update repository
      # Package will use whatever package manager the target server uses
      package:
        # Names of the application packages being installed
        name:
          # Variables being referenced for application packages
          - "{{ apache_package }}"
          - "{{ php_package }}"
        # Makes sure the application packages are the latest versions available
        state: latest
        # Action here is to update application index on server
        update_cache: yes
