# The following playbook is for targeting specific nodes
---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates on CentOS servers
      # Tags to provide meta data to plays
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install updates on Ubuntu servers
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:
    # Allows servers to unzip zip files from the command line
    - name: Install unzip
      package:
        name: unzip

    - name: Install Terraform
      # Requires the 'unzip' package installed previously
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.9.7/terraform_1.9.7_linux_amd64.zip
        dest: /usr/local/bin
        # Ansible won't look for the source directory locally
        remote_src: yes
        mode: 0755
        owner: root
        group: root

# Tasks following this will only ran against servers in the 'web_server' group
- hosts: web_servers

  become: true
  tasks:
    - name: install apache package, php support for and update repository for Ubuntu servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache package, php support for and update repository for CentOS servers
      tags: apache,httpd,centos
      dnf:
        name:
          - httpd
          - php
        state: latest
        when: ansible_distribution == "CentOS

    # The following play will copy the default HTML file to the web servers
    - name: Copy default HTML file for site
      tags: apache,apache2, httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        # No one will be able to change or access this file unless they have access to the root
        owner: root
        group: root
        # Permissions of the file
        mode: 0644

# Tasks following this will only ran against servers in the 'db_servers' group
- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package on Cent OS servers
      tags: centos,db,mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package on Ubuntu servers
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

# Tasks following this will only ran against servers in the 'file_server' group
- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
