# The following playbook is for targeting specific nodes
---
- hosts: all
  become: true
  pre_tasks:
    - name: Update repository cache on Ubuntu servers
      # Tags to provide meta data to plays
      tags: always
      dnf:
        update_cache: yes
        # Will not register a change when running this playbook
        changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Update repository cache on CentOS servers
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

# The following plays will run the taskbook of the specified roles against the specified groups
- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers