# The following playbook is for targeting specific nodes
---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates on CentOS servers
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install updates on Ubuntu servers
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

# Tasks following this will only ran against servers in the 'web_server' group
- hosts: web_servers

  become: true
  tasks:
    - name: install apache package, php support for and update repository for Ubuntu servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache package, php support for and update repository for CentOS servers
      tags: apache,httpd,centos
      dnf:
        name:
          - httpd
          - php
        state: latest
        when: ansible_distribution == "CentOS

# Tasks following this will only ran against servers in the 'db_servers' group
- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package on Cent OS servers
      tags: centos,db,mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package on Ubuntu servers
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

# Tasks following this will only ran against servers in the 'file_server' group
- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
