# The following playbook is for targeting specific nodes
---
- hosts: all
  become: true
  pre_tasks:
    - name: Update repository cache on Ubuntu servers
      # Tags to provide meta data to plays
      tags: always
      dnf:
        update_cache: yes
        # Will not register a change when running this playbook
        changed_when: false
      when: ansible_distribution == "CentOS"

    - name: Update repository cache on CentOS servers
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
    # This task add an ssh key for previously created user
    - name: Add SSH key for user
      tags: always
      authorized_key:
        user: russell
        # Key will allow the user to log into servers without a password/passphrase
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK1ZB9nEsRYHJktfzSqjfpFTOgIWLFoVGmAPCxAvDGiy ansible"

- hosts: workstations
  become: true
  tasks:
    # Allows servers to unzip zip files from the command line
    - name: Install unzip
      package:
        name: unzip

    - name: Install Terraform
      # Requires the 'unzip' package installed previously
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.9.7/terraform_1.9.7_linux_amd64.zip
        dest: /usr/local/bin
        # Ansible won't look for the source directory locally
        remote_src: yes
        mode: 0755
        owner: root
        group: root

# Tasks following this will only ran against servers in the 'web_server' group
- hosts: web_servers

  become: true
  tasks:
    - name: install apache package, php support for and update repository for Ubuntu servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache package, php support for and update repository for CentOS servers
      tags: apache,httpd,centos
      dnf:
        name:
          - httpd
          - php
        state: latest
        when: ansible_distribution == "CentOS

    # Play to start and enable the httpd/apache package on CentOS servers
    - name: Start httpd on CentOS servers
      tags: apache,centos
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution = CentOS
      # Will capture the state of httpd in a variable
      register: httpd

    # Will restart the httpd service using the previously captured 'httpd' variable
    - name: Restart httpd service on CentOS servers
      tags: apache, centos,httpd
      service:
        name: httpd
        state: restarted
      # Play will only run if 'httpd' variable is changed
      when: httpd.changed

    # Changing the admin e-mail on CentOS servers
    - name: Change e-mail address for admin
      tags: apache,centos,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^ServerAdmin"
        line: ServerAdmin russelljames202@gmail.com
      when: ansible_distribution == "CentOS"

    # The following play will copy the default HTML file to the web servers
    - name: Copy default HTML file for site
      tags: apache,apache2, httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        # No one will be able to change or access this file unless they have access to the root
        owner: root
        group: root
        # Permissions of the file
        mode: 0644

# Tasks following this will only ran against servers in the 'db_servers' group
- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package on Cent OS servers
      tags: centos,db,mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package on Ubuntu servers
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

# Tasks following this will only ran against servers in the 'file_server' group
- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
