- name: Install apache package and php support for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install apache package and php support for CentOS servers
  tags: apache,httpd,centos
  dnf:
    name:
      - httpd
      - php
    state: latest
    when: ansible_distribution == "CentOS

- name: Start httpd on CentOS servers
  tags: apache,centos
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution = CentOS
  register: httpd

- name: Restart httpd service on CentOS servers
  tags: apache, centos,httpd
  service:
    name: httpd
    state: restarted

  when: httpd.changed

- name: Change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerAdmin"
    line: ServerAdmin russelljames202@gmail.com
  when: ansible_distribution == "CentOS"

- name: Copy default HTML file for site
  tags: apache,apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
