- name: Add SSH key for user
  authorized_key:
    user: russell
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK1ZB9nEsRYHJktfzSqjfpFTOgIWLFoVGmAPCxAvDGiy ansible"

- name: Generate ssh_config file from template
  tags: ssh
  template: 
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd